server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Esta regla es vital para Angular: si no encuentra un archivo, redirige a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
