services:
  # 1. DATABASE CONTAINER
  mysql-db:
    image: mysql:8.0
    container_name: routemaster-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: routemaster_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # 2. BACKEND CONTAINER
  backend:
    build:
      context: ./backend
    container_name: routemaster-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/routemaster_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql-db

  # 3. FRONTEND CONTAINER
  frontend:
    build:
      context: ./frontend
    container_name: routemaster-frontend
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - backend

  # 4. CONTINUOUS INTEGRATION CONTAINER (Jenkins)
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: routemaster-jenkins
    restart: unless-stopped
    group_add:
      - "131"
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/routemaster:/opt/routemaster

  # 5. CLOUDFLARE TUNNEL (El puente con internet)
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: cloudflared --no-autoupdate tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    depends_on:
      - frontend
      - backend
      - jenkins

volumes:
  mysql-data:
