# API Keys
evolutivo.api_key_google=${GOOGLE_KEY}
evolutivo.api_key_openweather=${OPENWEATHER_KEY}
evolutivo.auth.secret-cookie-key=${COOKIE_AUTH_SECRET_KEY}

# Logging Configuration
logging.level.root=INFO
logging.level.es.metrica.sept25.evolutivo.service=DEBUG
logging.level.es.metrica.sept25.evolutivo.controller=DEBUG
logging.level.org.springframework.security=DEBUG

# SSL
server.port=8443
server.ssl.key-store=file:/opt/routemaster/keystore/keystore.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tfg-cert

# Database
spring.datasource.url=${DATABASE_URL}/evolutiva?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWD}

# docs/swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Cors
cors.allowed.origins=https://tfg.mariomartinmorilla.es
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
